buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.7.3"
        classpath "com.github.recloudstream:gradle:-SNAPSHOT"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.0"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

task make {
    dependsOn subprojects.collect { it.tasks.matching { t -> t.name == "assembleRelease" } }
}
