buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.3.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0"
        classpath "com.github.recloudstream:gradle:-SNAPSHOT"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

task make {
    dependsOn subprojects.collect { it.tasks.matching { task -> task.name == "assembleRelease" } }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
